# Generated by Django 3.2 on 2022-12-03 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_catagory_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
