# Generated by Django 3.2 on 2023-01-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='added_date',
            new_name='created_on',
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='sku',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
