# Generated by Django 3.2 on 2023-01-24 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_on',
        ),
    ]
